global using eShop.Domain.Entities;
global using eShop.ProductWebApi.Repositories.Interfaces;
global using LanguageExt.Common;
global using MediatR;
global using FluentValidation;
global using AutoMapper;
global using eShop.Domain.DTOs.Requests;
global using eShop.Domain.Exceptions;
global using Microsoft.EntityFrameworkCore;
global using eShop.ProductWebApi.Data;
global using eShop.Application;
global using Microsoft.AspNetCore.Mvc;
global using eShop.Domain.DTOs.Responses;
global using eShop.ProductWebApi.Repositories.Implementation;
global using LanguageExt;
global using Unit = LanguageExt.Unit;
global using MUnit = MediatR.Unit;
