global using AutoMapper;
global using eShop.AuthWebApi;
global using eShop.AuthWebApi.Data;
global using eShop.AuthWebApi.Services.Interfaces;
global using TokenHandler = eShop.AuthWebApi.Services.Implementation.TokenHandler;
global using eShop.Domain.Common;
global using eShop.Domain.DTOs;
global using eShop.Domain.DTOs.Requests;
global using eShop.Domain.DTOs.Responses;
global using eShop.Domain.DTOs.Messages;
global using eShop.Domain.Entities;
global using eShop.Domain.Exceptions;
global using eShop.AuthWebApi.Exceptions;
global using eShop.Domain.Options;
global using FluentValidation;
global using LanguageExt.Common;
global using MassTransit;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using MTokenHandler = Microsoft.IdentityModel.Tokens.TokenHandler;
global using System.Data;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Microsoft.IdentityModel.Tokens;
