// Global using directives

global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Security.Claims;
global using System.Text;
global using Azure.Storage.Blobs;
global using Blazored.LocalStorage;
global using eShop.Application.Extensions;
global using eShop.Domain.Common.Api;
global using eShop.Domain.Interfaces.Client;
global using eShop.Domain.Models;
global using eShop.Domain.Requests.Api.Auth;
global using eShop.Domain.Requests.Api.Cart;
global using eShop.Domain.Requests.Api.Comments;
global using eShop.Domain.Requests.Api.Favorites;
global using eShop.Domain.Requests.Api.Product;
global using eShop.Domain.Requests.Api.Review;
global using eShop.Domain.Requests.Api.Seller;
global using eShop.Domain.Responses.Api.Auth;
global using eShop.Domain.Types;
global using eShop.Infrastructure.Account;
global using eShop.Infrastructure.Services;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Newtonsoft.Json;
global using HttpMethods = eShop.Domain.Enums.HttpMethods;